### ISSUE TITLE
Valid Value range is empty on polylinePoints.getRouteBetweenCoordinates()

### ISSUE THREAD

**Issue by tayormi** [Dammyololade/flutter_polyline_points#1]
I get this error on call of polylinePoints.getRouteBetweenCoordinates()
```
Exception has occurred.
_Exception (Exception: RangeError (index): Invalid value: Valid value range is empty: 0)
```

**Comment by DavidSundar** [comment]
Same Error here,

Unhandled Exception: Exception: RangeError (index): Invalid value: Valid value range is empty: 0

**Comment by Joban1996** [comment]
Same Exception here.
Any solution ?

**Comment by uolrdChet** [comment]
same Exception. Soln pls.

**Comment by khanhsiclo** [comment]
You need to enable Directions API in https://console.cloud.google.com/apis/library
Then add billing account for Google Cloud Platform: https://console.cloud.google.com/billing
The API is no longer free

**Comment by uolrdChet** [comment]
10ks.
