### ISSUE TITLE
Roundabout is not drawn correctly

### ISSUE THREAD

**Issue by leonardoayres** [Dammyololade/flutter_polyline_points#11]
I live in a city with a lot of roundabouts, and when trying your package, i've noted that evertytime i'm aproaching a roundabout, it draws the polylines all around the circle even if i'm just passing by (like taking a left turn to skipt the roundabout) and not entering the roundabout.

**Comment by Dammyololade** [comment]
Hi, can you send me the coordinates or a link to a sample project to try out this issue?

**Comment by leonardoayres** [comment]
I got no isolated project with the issue, but on the link below i've shared 2 images that shows the problem.

On each image there is is my walked path (in blue) and in red the path that the polylines were automatically drawn.

https://drive.google.com/open?id=1W5IYdgzmsDp4HqZ0oLX2WFGaRBXzDQqh
