### ISSUE TITLE
Waypoint LatLng pass

### ISSUE THREAD

**Issue by ziasultan2** [Dammyololade/flutter_polyline_points#16]
In plugin example you show
 wayPoints: [
          PolylineWayPoint(location: "location")
        ]);

In your PolylineWayPoints file your comment
   /// as a LatLng, as a google.maps.Place object

I want to pass LatLng to PolyLineWayPoint location. I tried to pass LatLng but it doesn't work. What is the way to pass LatLng there

**Comment by ismetatakli** [comment]
+++

**Comment by Dammyololade** [comment]
the waypoint documentation has been updated

/// the location of the waypoint,
  /// You can specify waypoints using the following values:
  /// --- Latitude/longitude coordinates (lat/lng): an explicit value pair. (-34.92788%2C138.60008 comma, no space),
  /// --- Place ID: The unique value specific to a location. This value is only available only if
  ///     the request includes an API key or Google Maps Platform Premium Plan client ID (ChIJGwVKWe5w44kRcr4b9E25-Go
  /// --- Address string (Charlestown, Boston,MA)
  /// ---
  String location;

**Comment by ziasultan2** [comment]
Hi dear thank you for this update. Can u please add the estimated time and distance. It'll be great healpful

**Comment by ismetatakli** [comment]
> the waypoint documentation has been updated
> 
> /// the location of the waypoint,
> /// You can specify waypoints using the following values:
> /// --- Latitude/longitude coordinates (lat/lng): an explicit value pair. (-34.92788%2C138.60008 comma, no space),
> /// --- Place ID: The unique value specific to a location. This value is only available only if
> /// the request includes an API key or Google Maps Platform Premium Plan client ID (ChIJGwVKWe5w44kRcr4b9E25-Go
> /// --- Address string (Charlestown, Boston,MA)
> /// ---
> String location;


can you write an example?

**Comment by shindyxinyi** [comment]
Tried with all the suggestion above. Only works for passing location name but not place ID and latitude, longitude.

**Comment by RenatBack** [comment]
The polyline is not displayed on the map. Please tell me how to fix it.

**Comment by ismetatakli** [comment]
> > the waypoint documentation has been updated
> > /// the location of the waypoint,
> > /// You can specify waypoints using the following values:
> > /// --- Latitude/longitude coordinates (lat/lng): an explicit value pair. (-34.92788%2C138.60008 comma, no space),
> > /// --- Place ID: The unique value specific to a location. This value is only available only if
> > /// the request includes an API key or Google Maps Platform Premium Plan client ID (ChIJGwVKWe5w44kRcr4b9E25-Go
> > /// --- Address string (Charlestown, Boston,MA)
> > /// ---
> > String location;
> 
> can you write an example?
> 
> ![Ek Açıklama 2020-07-03 112839](https://user-images.githubusercontent.com/23284192/86449152-69cf0700-bd20-11ea-96ed-6248c6b4959b.png)
> 
> is not working for me

+++

**Comment by yusufmustu** [comment]
It works for location name but other methods (latitude / longitude and ID) don't work. Anybody find a solution?

**Comment by Dammyololade** [comment]
Hi, the update is now available on pub
https://pub.dev/packages/flutter_polyline_points/install

**Comment by akbarpulatov** [comment]
[PolylineWayPoint(location: "41.334670%2C69.264342", stopOver: true),]
[PolylineWayPoint(location: "${latitude}%2C${longitude}", stopOver: true),]
Is this the template? If so it is not working for me
status is "NOT_FOUND"

**Comment by AnasYousuf-PZ** [comment]
where's the documentation of implementing multiple waypoints ?? using coordinates. @Dammyololade

**Comment by mavalos93** [comment]
this worked for me:
Flutter 3.13.4 • stable channel •
https://github.com/flutter/flutter.git
Marco • review 367f9ea16b (3 weeks ago) • 2023-09-12 23:27:53
-0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0
-------------------------------------------------- --------------------------
Json waypoint:
[
    {
      "location": {
        "lat": -xx.xxxxxxx
        "lng": -xx.xxxxxxx
      },
      "scale": false
    },
    {
      "location": {
        "lat": -xx.xxxxxxx
        "lng": -xx.xxxxxxx
      },
      "scale": false
    }
]

Process json to PolylineWayPoint:

   List<PolylineWayPoint> getWayPoints() {
      List<PolylineWayPoint> resultList = [];

      List<dynamic> waypoint location =
          jsonDecode(widget.ordersAssignments.pathRoute!);
      for (var element in waypointLocation) {
        resultList.add(PolylineWayPoint(
            location:
                '${item['location']['lat']},${item['location']['lng']}'));
      }

      return resultList;
    }
// set in the flutter_polyline_points library:
     coordinates = await polylinePoints.getRouteBetweenCoordinates(
        Security().getMapsApiKey(),
        wayPoints: getWayPoints(),// --> process method
        optimizeWaypoints: true, // --> set parameter optimizeWaypoints true
        travel mode: travel mode.driving,
        LatLngPoint( -xx.xxxxxxx,
            -xx.xxxxxxx),
        LatLngPoint( -xx.xxxxxxx,
             -xx.xxxxxxx),
      );

if(getWayPoints().isNotEmpty){
addPolyline(.......);
}
