### ISSUE TITLE
Only one Way point is working.

### ISSUE THREAD

**Issue by Anuj-Jha** [Dammyololade/flutter_polyline_points#18]
Hi,
I am using this package to show Polyline with multiple Waypoints on Google map. But only the first Waypoint in the array is considered in the polyline, rest all are ignored.

Following is the request for source and destination with 2 waypoints, that I can see in the console -

https://maps.googleapis.com/maps/api/directions/json?origin=26.8186007%2C80.9073366&destination=26.8942524%2C80.9453734&mode=driving&avoidHighways=false&avoidFerries=true&avoidTolls=false&key=GOOGLE_API_KEY&waypoints=%5B%7B%22location%22%3A%22Bara+Imambara%2C+Machchhi+Bhavan%2C+Lucknow%2C+Uttar+Pradesh%2C+India%22%2C%22stopover%22%3Atrue%7D%2C%7B%22location%22%3A%22Naka+Market%2C+Unnamed+Road%2C+Arya+Nagar%2C+Charbagh%2C+Lucknow%2C+Uttar+Pradesh%2C+India%22%2C%22stopover%22%3Atrue%7D%5D

Please let me know what can be the issue?

Thanks in advance,
Anuj Jha

**Comment by andreribeiropinto104** [comment]
I have the exactly same issue.

Any solution?
Thanks in advance.

**Comment by Dammyololade** [comment]
Hi, the issues has been resolved 
https://pub.dev/packages/flutter_polyline_points/install
