### ISSUE TITLE
getRouteBetweenCoordinates() returns an empty list

### ISSUE THREAD

**Issue by Omar-Belghaouti** [Dammyololade/flutter_polyline_points#22]
I tried many times to figure out what was the problem but I did not get any clue, here is my snippet code:
```dart
void setPolylines() async {

    PolylineResult result = await polylinePoints.getRouteBetweenCoordinates(
      GOOGLE_API_KEY,
      PointLatLng(SOURCE_LOCATION.latitude, SOURCE_LOCATION.longitude),
      PointLatLng(DEST_LOCATION.latitude, DEST_LOCATION.longitude),
      travelMode: TravelMode.driving,
    );

    print(result);
    print(result.points);

    if (result.points.isNotEmpty) {
      result.points.forEach((PointLatLng point) {
        polylineCoordinates.add(LatLng(point.latitude, point.longitude));
      });
    }

    setState(() {
      Polyline polyline = Polyline(
          polylineId: PolylineId('poly'),
          color: Colors.blue,
          points: polylineCoordinates);

      _polylines.add(polyline);
    });
  }
```

**Comment by ismetatakli** [comment]
Check the url in the console after running. It can give you detailed information. For example 'Billing is not activated'

**Comment by Omar-Belghaouti** [comment]
> Check the url in the console after running. It can give you detailed information. For example 'Billing is not activated'

You are absolutely right, here's what I got:
{
   "error_message" : "You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started",
   "routes" : [],
   "status" : "REQUEST_DENIED"
}

**Comment by Milan-Bhingradiya** [comment]
hii i am  getting same but error msg is This API project is not authorized to use this API.

and i have api key without  billing account..

can u help me ?

it must? to create billing account for only demo app  project?
