### ISSUE TITLE
wayPoints error

### ISSUE THREAD

**Issue by ismetatakli** [Dammyololade/flutter_polyline_points#29]
when i try to add waypoints i get an error.

`_TypeError (type 'MappedListIterable<PolylineWayPoint, String>' is not a subtype of type 'List<String>')`

Can you show me an example of adding coordinates at waypoints. the examples you have given do not work correctly

**Comment by kawaldeep2507** [comment]
Change 
 List<String> wayPointsArray = wayPoints.map((point) => point.location.toString());

in network_util to this and it will work.
      
List<String> wayPointsArray=[];
      for(var wayString in wayPoints){
        wayPointsArray.add(wayString.location);
      }

**Comment by javico2609** [comment]
`wayPoints.forEach((point) => wayPointsArray.add(point.location)).ToList();`

**Comment by maheshmnj** [comment]
> `wayPoints.forEach((point) => wayPointsArray.add(point.location)).ToList();`

can you please provide more details on this ?

**Comment by rafay-tariq** [comment]
received this same issue when adding the waypoints. 

` code

     PolylineResult result = await polylinePoints.getRouteBetweenCoordinates(
        googleAPIKey,
        PointLatLng(31.4805, 74.3239),
        PointLatLng(31.4697, 74.2728),
        travelMode: TravelMode.driving,
        wayPoints: [PolylineWayPoint(location: "Sabo, Yaba Lagos Nigeria")]
        );`

**Comment by rafay-tariq** [comment]
yes when i update this above line that you have provided this error goes out but now it added the waypoints in the API as 



https://maps.googleapis.com/maps/api/directions/json?origin=31.4805%2C74.3239&destination=31.4697%2C74.2728&mode=driving&avoidHighways=false&avoidFerries=true&avoidTolls=false&key=YOUR_API_KEY&waypoints=faisalabad

BUT it should pass it as &waypoints=via:faisalabad even i pass the bool value as false



wayPoints: [PolylineWayPoint(location: "faisalabad", stopOver: false)],

**Comment by adanluna** [comment]
I had the same error and I fixed with @kawaldeep2507 solution, thanks man!

**Comment by Dammyololade** [comment]
The next release in couple of hours will resolve this
