### ISSUE TITLE
lat long change error

### ISSUE THREAD

**Issue by shree-krishna-gapi** [Dammyololade/flutter_polyline_points#32]
double _originLatitude = 6.5212402, _originLongitude = 3.3679965;
  double _destLatitude = 6.849660, _destLongitude = 3.648190;
  when i try to change this line as is not working 
  double _originLatitude = 27.6765179, _originLongitude = 85.3471198;
  double _destLatitude = 27.7097955, _destLongitude = 85.3264372;

**Comment by Dammyololade** [comment]
Can u share the exact error you are getting, thanks

**Comment by Dammyololade** [comment]
closing this because of no response, kindly open a new issue if you experience the same problem
