### ISSUE TITLE
Can not see polly line

### ISSUE THREAD

**Issue by abhib842** [Dammyololade/flutter_polyline_points#33]
Hi 
I can not see polly line even after change the coordinate i can see the error in log.

Syncing files to device Redmi Note 6 Pro...
Restarted application in 1,559ms.
I/Google Maps Android API(29203): Google Play services package version: 203315028
E/flutter (29203): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'MappedListIterable<PolylineWayPoint, String>' is not a subtype of type 'List<String>'
E/flutter (29203): #0      NetworkUtil.getRouteBetweenCoordinates (package:flutter_polyline_points/src/network_util.dart:37:20)
E/flutter (29203): #1      PolylinePoints.getRouteBetweenCoordinates (package:flutter_polyline_points/flutter_polyline_points.dart:31:23)
E/flutter (29203): #2      _MapScreenState._getPolyline (package:flutter_app/app_screens/map_polly_line.dart:88:50)

**Comment by Dammyololade** [comment]
this is going to be fixed in the next release
