### ISSUE TITLE
Polyline not drawing on map

### ISSUE THREAD

**Issue by rizalsafril** [Dammyololade/flutter_polyline_points#37]
Hi..I have an issue here. everything is working fine except polyline is not drawing the street line between destination and origin. any update on this? 

Thanks for your time
cheers

**Comment by Dammyololade** [comment]
Can u check your logs for possible errors thrown?
Also did you enable billing on your google cloud console for the api-key you are using?

**Comment by yousefff7** [comment]
I got the same issue :( , I already enabled billing in my account and there is no errors in logs.
Thanks for your effort,

**Comment by ghike** [comment]
I'm having this error too.
I've told flutter to print the errors on my terminal, here's the log:

`flutter: Instance of 'PolylineResult'
flutter: 
flutter: OK
flutter: [lat: -23.51337 / longitude: -47.47415, lat: -23.51266 / longitude: -47.47453, lat: -23.51201 / longitude: -47.47487, lat: -23.51217 / longitude: -47.47523, lat: -23.51232 / longitude: -47.47559, lat: -23.51329 / longitude: -47.4751, lat: -23.51464 / longitude: -47.47438, lat: -23.51524 / longitude: -47.47405, lat: -23.5155 / longitude: -47.47434, lat: -23.51556 / longitude: -47.47453, lat: -23.51554 / longitude: -47.47538, lat: -23.51553 / longitude: -47.47622, lat: -23.51551 / longitude: -47.47742, lat: -23.51547 / longitude: -47.47935, lat: -23.51549 / longitude: -47.47974, lat: -23.51557 / longitude: -47.48016, lat: -23.51621 / longitude: -47.48222, lat: -23.51654 / longitude: -47.48336, lat: -23.51683 / longitude: -47.48433, lat: -23.51735 / longitude: -47.48612, lat: -23.51736 / longitude: -47.48646, lat: -23.51735 / longitude: -47.48661, lat: -23.51729 / longitude: -47.48665, lat: -23.51725 / longitude: -47.48671, lat: -23.51723 / longitude: -47.48679, lat: -23.51724 / longitude: -47.48686, lat: -23.5173 / longitude: -47.48697, lat: -23.51736 / longitude: -47.487, lat: -23.51737 / longitude: -47.48747, lat: -23.51736 / longitude: -47.48803, lat: -23.51732 / longitude: -47.48841, lat: -23.51736 / longitude: -47.4888, lat: -23.51743 / longitude: -47.48906, lat: -23.51752 / longitude: -47.48926, lat: -23.51768 / longitude: -47.48955, lat: -23.51775 / longitude: -47.48973, lat: -23.51775 / longitude: -47.4898, lat: -23.51773 / longitude: -47.48997, lat: -23.51769 / longitude: -47.49007, lat: -23.51802 / longitude: -47.49017, lat: -23.51963 / longitude: -47.49071, lat: -23.52133 / longitude: -47.49117, lat: -23.52144 / longitude: -47.49119, lat: -23.52226 / longitude: -47.4913, lat: -23.52245 / longitude: -47.49131, lat: -23.52252 / longitude: -47.49154, lat: -23.52258 / longitude: -47.49176, lat: -23.52239 / longitude: -47.49244, lat: -23.52222 / longitude: -47.49304, lat: -23.5225 / longitude: -47.49314]
flutter: it works!`

And here's the source code:
`void setPolylines() async {
    PolylineResult result = await polylinePoints.getRouteBetweenCoordinates(
        googleAPIKey,
        PointLatLng(currentLocation.latitude, currentLocation.longitude),
        PointLatLng(
            destinationLocation.latitude, destinationLocation.longitude));

    print(currentLocation.latitude);
    print(currentLocation.longitude);
    print(destinationLocation.latitude);
    print(destinationLocation.longitude);
    print(result);
    print(result.errorMessage);
    print(result.status);
    print(result.points);

    // Se o resultado para os pontos obtidos não forem vazios, adiciona cada um dos
    // pontos devolvidos para a API na variável polylineCoordinates
    if (result.points.isNotEmpty) {
      result.points.forEach((PointLatLng point) {
        polylineCoordinates.add(LatLng(point.latitude, point.longitude));
      });

      // Configurando o setState para exibir a polyline para o usuário.
      setState(() {
        _polylines.add(Polyline(
            width: 5,
            polylineId: PolylineId("poly"),
            color: Color.fromARGB(255, 40, 122, 198),
            points: polylineCoordinates));
        print("it works!");
      });
    }
  }`

**Comment by ghike** [comment]
I was having the same problem. Then, I was reviewing my code and I forgot to call the `polylines` property inside my `GoogleMap()`.

I've just added `polylines: _polylines` and _voilà_! It worked like a charm!

**Comment by rizalsafril** [comment]
> I was having the same problem. Then, I was reviewing my code and I forgot to call the `polylines` property inside my `GoogleMap()`.
> 
> I've just added `polylines: _polylines` and _voilà_! It worked like a charm

**Comment by rizalsafril** [comment]
> Can u check your logs for possible errors thrown?
> Also did you enable billing on your google cloud console for the api-key you are using?

no errors thrown..and I have enabled my billing. everythings work fine, markers are displayed on map, only polyline is missing

**Comment by rizalsafril** [comment]
> I was having the same problem. Then, I was reviewing my code and I forgot to call the `polylines` property inside my `GoogleMap()`.
> 
> I've just added `polylines: _polylines` and _voilà_! It worked like a charm!

can u show me your code? because I did the same but polyline is still missing

**Comment by rizalsafril** [comment]
import 'dart:async';

import 'package:beliaja/database/location/device_location.dart';

import 'package:beliaja/shared/secret_api.dart';
import 'package:beliaja/shared/warna.dart';
import 'package:flutter/material.dart';
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:location/location.dart';

class MapLocation extends StatefulWidget {
  MapLocation({Key key}) : super(key: key);

  @override
  _MapLocationState createState() => _MapLocationState();
}

class _MapLocationState extends State<MapLocation> {
  Completer<GoogleMapController> _controller = Completer();
  double destlat = 5.552780;
  double destlong = 95.298019;

  ///LocationData to save
  ///latitude and longitude
  Location location = Location();
  Future<LocationData> _currentLocation;

  ////Custom icon
  BitmapDescriptor originIcon;
  BitmapDescriptor destIcon;

  ///Polyline inside Googlemap
  Map<MarkerId, Marker> markers = {};
  Map<PolylineId, Polyline> polylines = {};
  List<LatLng> polylineCoordinates = [];
  PolylinePoints polylinePoints = PolylinePoints();
  String googleAPiKey = Secrets.API_KEY;

  @override
  void initState() {
    super.initState();
    _createIcon();
    _currentLocation = LocationDevice().getLocation();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Warna.green,
        title: Text(
          "Lokasi Peta",
          style: TextStyle(color: Colors.white),
        ),
      ),
      body: Stack(
        children: [
          FutureBuilder(
            future: LocationDevice().checkDevice(),
            builder: (BuildContext context, snapshot) {
              switch (snapshot.connectionState) {
                case (ConnectionState.waiting):
                  return Center(
                    child: CircularProgressIndicator(),
                  );
                default:
                  return Container();
              }
            },
          ),
          FutureBuilder(
            future: _currentLocation,
            builder: (BuildContext context, AsyncSnapshot<LocationData> data) {
              switch (data.connectionState) {
                case (ConnectionState.waiting):
                  return Center(
                    child: CircularProgressIndicator(),
                  );
                default:
                  return GoogleMap(
                    mapType: MapType.normal,
                    myLocationEnabled: true,
                    compassEnabled: true,
                    initialCameraPosition: CameraPosition(
                      target: LatLng(data.data.latitude, data.data.longitude),
                      // tilt: 59.440717697143555,
                      zoom: 15.0,
                    ),
                    onMapCreated: (GoogleMapController controller) {
                      _controller.complete(controller);

                      ///Calling polyline
                      _getPolyline(
                        data.data.latitude,
                        data.data.longitude,
                        destlat,
                        destlong,
                      );

                      /// origin marker
                      _addMarker(
                          LatLng(
                            data.data.latitude,
                            data.data.longitude,
                          ),
                          "Lokasi anda",
                          originIcon);

                      /// destination marker
                      _addMarker(
                          LatLng(
                            destlat,
                            destlong,
                          ),
                          "Tujuan",
                          destIcon);
                    },
                    markers: Set<Marker>.of(markers.values),
                    polylines: Set<Polyline>.of(polylines.values),
                    circles: Set.from([
                      Circle(
                        circleId: CircleId("circle"),
                        center: LatLng(data.data.latitude, data.data.longitude),
                        fillColor: Colors.blue.withOpacity(0.9),
                        strokeColor: Colors.blue.withOpacity(0.9),
                        radius: 1000,
                      )
                    ]),
                  );
              }
            },
          ),
        ],
      ),
    );
  }

  ////We make Icon function. This icon
  ///will be inserted inside google map as marker
  Future _createIcon() async {
    BitmapDescriptor.fromAssetImage(ImageConfiguration(size: Size(12, 12)),
            "assets/images/pin-origin-128.png")
        .then((value) => originIcon = value);

    BitmapDescriptor.fromAssetImage(
            ImageConfiguration(size: Size(12, 12)), "assets/images/pin-128.png")
        .then((value) => destIcon = value);
  }

  ///Function to add marker
  _addMarker(LatLng position, String id, BitmapDescriptor descriptor) {
    MarkerId markerId = MarkerId(id);
    Marker marker =
        Marker(markerId: markerId, icon: descriptor, position: position);
    markers[markerId] = marker;
  }

  ///Cal polyline
  _addPolyLine() {
    PolylineId id = PolylineId("poly");
    Polyline polyline = Polyline(
        polylineId: id, color: Colors.red, points: polylineCoordinates);
    polylines[id] = polyline;
    setState(() {});
  }

  ////Add polyline to map
  _getPolyline(double _originLatitude, double _originLongitude,
      double _destLatitude, double _destLongitude) async {
    PolylineResult result = await polylinePoints.getRouteBetweenCoordinates(
        googleAPiKey,
        PointLatLng(_originLatitude, _originLongitude),
        PointLatLng(_destLatitude, _destLongitude),
        travelMode: TravelMode.driving,
        wayPoints: [PolylineWayPoint(location: "Your Location, Indonesia")]);
    if (result.points.isNotEmpty) {
      result.points.forEach((PointLatLng point) {
        polylineCoordinates.add(LatLng(point.latitude, point.longitude));
      });
    }
    _addPolyLine();
  }
}

=============Class location===========
Location location = new Location();
bool _serviceEnabled;
PermissionStatus _permissionGranted;

class LocationDevice {
  Future<bool> checkDevice() async {
    try {
      _serviceEnabled = await location.serviceEnabled();
      _permissionGranted = await location.hasPermission();

      if (!_serviceEnabled) {
        _serviceEnabled = await location.requestService();
        if (!_serviceEnabled) {
          return false;
        }
      }
      if (_permissionGranted == PermissionStatus.denied) {
        _permissionGranted = await location.requestPermission();
        if (_permissionGranted != PermissionStatus.granted) {
          return false;
        }
      }

      return true;
    } on PlatformException catch (e) {
      print("Pesan Kesalahan ==> $e");
      return false;
    }
  }

  Future<double> getLat() async {
    var lokasi;
    lokasi = await location.getLocation();

    return lokasi.latitude;
  }

  Future<LocationData> getLocation() async {
    return await location.getLocation();
  }
}

**Comment by Dammyololade** [comment]
Can you share a sample code or possibly a demo project to replicate this issue you are having?

**Comment by rizalsafril** [comment]
> Can you share a sample code or possibly a demo project to replicate this issue you are having?

Thanks...already posted above..

**Comment by Dammyololade** [comment]
Or can you print the result of await polylinePoints.getRouteBetweenCoordinates()? and also, remove waypoint and try making the request, lets see if its going to come back with a result

**Comment by ericel** [comment]
This happens to me with coordinates in South Korea.
Works fine with US coordinates.
But with Korean coordinates, it returns result.points is an empty list [].

What can be the problem?

**Comment by rizalsafril** [comment]
> Or can you print the result of await polylinePoints.getRouteBetweenCoordinates()? and also, remove waypoint and try making the request, lets see if its going to come back with a result

The result of await polylinePoints is **Instance of 'PolylineResult'**

**Comment by Dammyololade** [comment]
@ericel av u tried calling the google api directly, probably from postman, i think you might have this issue if google doesn't have data for your request

**Comment by Dammyololade** [comment]
> > Or can you print the result of await polylinePoints.getRouteBetweenCoordinates()? and also, remove waypoint and try making the request, lets see if its going to come back with a result
> 
> The result of await polylinePoints is **Instance of 'PolylineResult'**

can you check the points property of the result, what's the length? is there any coordinate return?

**Comment by ericel** [comment]
> @ericel av u tried calling the google api directly, probably from postman, i think you might have this issue if google doesn't have data for your request

The map displays the markers. I will think it means google has the data?

**Comment by Dammyololade** [comment]
> > @ericel av u tried calling the google api directly, probably from postman, i think you might have this issue if google doesn't have data for your request
> 
> The map displays the markers. I will think it means google has the data?

The amp can show the marker because you are plotting on a coordinate, but that does not mean, google has information about the direction between that coordinate and another location

**Comment by ericel** [comment]
You are right! 

> > > @ericel av u tried calling the google api directly, probably from postman, i think you might have this issue if google doesn't have data for your request
> > 
> > 
> > The map displays the markers. I will think it means google has the data?
> 
> The amp can show the marker because you are plotting on a coordinate, but that does not mean, google has information about the direction between that coordinate and another location

You are right! That should be the only explanation for the behavior.

**Comment by rizalsafril** [comment]
> > > Or can you print the result of await polylinePoints.getRouteBetweenCoordinates()? and also, remove waypoint and try making the request, lets see if its going to come back with a result
> > 
> > 
> > The result of await polylinePoints is **Instance of 'PolylineResult'**
> 
> can you check the points property of the result, what's the length? is there any coordinate return?

it returns null. I think I will go with your conclusion. it seems google has no information about particular location. Thanks @ericel for your additional info

**Comment by rizalsafril** [comment]
@Dammyololade thanks for your support. I updated my info, the polyline starts drawing now after I activated **Direction API** in google cloud platform..I think that caused a problem.

**Comment by Dammyololade** [comment]
wow, good to hear that.
