### ISSUE TITLE
I'm trying to display polylines as per Google road map on my flutter app using authorized google key which is working fine in android app. But In flutter app it's showing unauthorised key.

### ISSUE THREAD

**Issue by bhagyashrieducloud** [Dammyololade/flutter_polyline_points#45]
I'm using google_maps_flutter: ^0.5.11+1 and flutter_polyline_points: ^0.1.0 plugin.

When i'm debugging internal libraries i'm getting following errors in response -> 
{ 
"error_message" : "This IP, site or mobile application is not authorized to use this API key. Request received from IP address 2405:204:969c:11f6::24b9:a8a4, with empty referer", 
"routes" : [], 
"status" : "REQUEST_DENIED"
 }

My code is in this file->
[Google_Map_Page.txt](https://github.com/Dammyololade/flutter_polyline_points/files/5988540/Google_Map_Page.txt)

**Comment by xlfdyzcs** [comment]
+1

**Comment by xlfdyzcs** [comment]
![image](https://user-images.githubusercontent.com/36396699/108704445-fe53d700-7546-11eb-989d-e3a17455dee7.png)
![image](https://user-images.githubusercontent.com/36396699/108704530-1cb9d280-7547-11eb-81d6-9f4aed263c9a.png)

**Comment by xlfdyzcs** [comment]
https://developers.google.com/maps/documentation/directions/cloud-setup

**Comment by xlfdyzcs** [comment]
> https://developers.google.com/maps/documentation/directions/cloud-setup

根据上面的说明，在
![image](https://user-images.githubusercontent.com/36396699/109387280-7fdaa900-793b-11eb-813f-adf23940599e.png)c此处允许  directions api
