### ISSUE TITLE
Issue with virtual display size , It says created display size is larger than device screen size.

### ISSUE THREAD

**Issue by prabhunath111** [Dammyololade/flutter_polyline_points#5]
Below error i am getting...

Creating a virtual display of size: [1080, 2210] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2131]

**Comment by Dammyololade** [comment]
Hello, has this been resolved now?

**Comment by routsrv** [comment]
Hello, I'm getting the same error.
Does anyone have idea how to fix it?

**Comment by prabhunath111** [comment]
> Hello, I'm getting the same error.
> Does anyone have idea how to fix it?

You can resolve this by write example app code in your project after installation
 this plugin...

**Comment by prabhunath111** [comment]
> Hello, has this been resolved now?

I found another way and it's working...

**Comment by routsrv** [comment]
@prabhunath111  Can you please explain how you fix it? Also getting more bottom margin in ios.
Thank you

**Comment by routsrv** [comment]
@prabhunath111  Can you help with this?

**Comment by aboutmydreams** [comment]
same problem

**Comment by Dammyololade** [comment]
Hi can't seem to be able to reproduce this error, can you please share your sample usage or the output of flutter doctor

**Comment by RedCuckoo** [comment]
@Dammyololade I am getting this error, while wrapping [WebView](https://pub.dev/packages/webview_flutter) into a SizedBox, which is wrapped into a ListView and setting bigger size than my physical device is. 

It might seem a not very good structure, but I ended up with it trying to add pull to refresh gesture to the WebView (webview_flutter plugin).

Here is a simple snippet how to reproduce it:

<pre><code>@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter WebView example'),
      ),
      body: ListView(
      children:[SizedBox.fromSize(
        size:Size(100,1000),
        child: WebView(initialUrl: "https://flutter.dev/", javascriptMode: JavascriptMode.unrestricted,),
      ),]),
    );</code></pre>

<details><summary>flutter doctor -v</summary>
[√] Flutter (Channel master, 1.18.0-14.0.pre.22, on Microsoft Windows [Version 10.0.18363.778], locale uk-UA)
    • Flutter version 1.18.0-14.0.pre.22 at C:\flutter
    • Framework revision 3519bec6c4 (10 hours ago), 2020-05-08 00:34:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\momot\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\momot\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.5731

[!] VS Code, 64-bit edition (version 1.44.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 5 • 43150aa4 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
</details>

My flutter is on master.

**Comment by Dammyololade** [comment]
This issue has nothing to do with this plugin, kindly open an issue on flutter, thanks

**Comment by Masrafi** [comment]
I want to show json pdf file. But it show that's kind of problem:

I/flutter ( 9329): tenderimage/Dec08/Dec08_Dhaka Navy-7A.pdf
W/PlatformViewsController( 9329): Creating a virtual display of size: [1440, 3500] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 2701].
D/com.shockwave.pdfium.PdfiumCore( 9329): Starting PdfiumAndroid 1.9.0
D/jniPdfium( 9329): Init FPDF library
D/jniPdfium( 9329): Destroy FPDF library

**Comment by deepak-0811** [comment]
W/PlatformViewsController(26743): Creating a virtual display of size: [1080, 2210] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2134].

**Comment by amitsingh6391** [comment]
W/PlatformViewsController( 2592): Creating a virtual display of size: [1575, 700] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1440, 2392].
D/com.shockwave.pdfium.PdfiumCore( 2592): Starting PdfiumAndroid 1.9.0
D/jniPdfium( 2592): Init FPDF library
D/jniPdfium( 2592): Destroy FPDF library

**Comment by prabhunath111** [comment]
> @prabhunath111 Can you help with this?

Did you solve it?

**Comment by prabhunath111** [comment]
> Same problem can anyone help me.
> 
> W/PlatformViewsController(26743): Creating a virtual display of size: [1080, 2210] may result in problems([flutter/flutter#2897](https://github.com/flutter/flutter/issues/2897) is larger than the device screen size: [1080, 2134].

Did you solve it?

**Comment by prabhunath111** [comment]
> Same problem can anyone help me.
> 
> W/PlatformViewsController(26743): Creating a virtual display of size: [1080, 2210] may result in problems([flutter/flutter#2897](https://github.com/flutter/flutter/issues/2897) is larger than the device screen size: [1080, 2134].

Did you solve it?

**Comment by surajsahani** [comment]
use a placeholder with fixed height and width work for me
  PDF.network(
                      'https://google-developer-training.github.io/android-developer-fundamentals-course-concepts/en/android-developer-fundamentals-course-concepts-en.pdf',
                      height:  MediaQuery.of(context).size.height,

                      width: MediaQuery.of(context).size.width,
                      placeHolder: Image.asset("assets/images/pdf.png",
                          height: 200, width: 100),
                    ),

**Comment by naseerx** [comment]
PlatformViewsController(30359): Creating a virtual display of size: [1080, 2400] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size:
