### ISSUE TITLE
why use http 0.13.0-nullsafety.0?

### ISSUE THREAD

**Issue by smasinde** [Dammyololade/flutter_polyline_points#53]
It's breaking a lot and 0.13.0 is null safe....

Because no versions of flutter_polyline_points match >0.2.6 <0.3.0 and flutter_polyline_points 0.2.6 depends on http ^0.13.0-nullsafety.0, flutter_polyline_points ^0.2.6 requires http ^0.13.0-nullsafety.0.

**Comment by wrtisans** [comment]
how do you fix this? I've the same problem

**Comment by Dammyololade** [comment]
This has been resolved
