### ISSUE TITLE
Nullsafety support 

### ISSUE THREAD

**Issue by alvincast** [Dammyololade/flutter_polyline_points#54]
hello there i would like to know when null safety will be supported ?

**Comment by namchuai** [comment]
@Dammyololade, please review #49 and merge.

**Comment by rakeshlanjewar** [comment]
@Dammyololade When we should expect that it will land in pub.dev

**Comment by rakeshlanjewar** [comment]
@Dammyololade please see #56 

And sorry i have published this package with another name untill you merge the pull request

**Comment by serraojoao** [comment]
Hello, 
@Dammyololade any expected timeline for the null safety release? 
thank you,

**Comment by Dammyololade** [comment]
The package now supports null safety
