### ISSUE TITLE
avoidTolls bug

### ISSUE THREAD

**Issue by nizarhdt** [Dammyololade/flutter_polyline_points#55]
avoidTolls is not working

**Comment by hananda** [comment]
yes, becaus this plugin doesn't follow google format param for avoid tolls below

Directions may be calculated that adhere to certain restrictions. Restrictions are indicated by use of the avoid parameter, and an argument to that parameter indicating the restriction to avoid. The following restrictions are supported:

avoid=tolls
avoid=highways
avoid=ferries
It's possible to request a route that avoids any combination of tolls, highways and ferries by passing both restrictions to the avoid parameter. For example: avoid=tolls|highways|ferries.
