### ISSUE TITLE
How to get multi polylines

### ISSUE THREAD

**Issue by buimanhhungit** [Dammyololade/flutter_polyline_points#61]
Please let me know
How to get multi polylines?

**Comment by serraojoao** [comment]
you can add multiple polylines to the set list

**Comment by buimanhhungit** [comment]
I can add but how to get multiple polyline between 2 points

**Comment by Dammyololade** [comment]
This is now available on [version 2.0.0](https://pub.dev/packages/flutter_polyline_points)
