### ISSUE TITLE
Getting 'REQUEST_DENIED' in response status. 

### ISSUE THREAD

**Issue by ayaanpathan** [Dammyololade/flutter_polyline_points#64]
Hi, I am trying to add polylines to my map, I have enabled maps for android, iOS and directions API. I am still getting this error.

**Comment by iKlsR** [comment]
Late but for anyone who sees this, you need to enable billing.

**Comment by TetrixGauss** [comment]
@iKlsR i have enabled the billing in my project but the same response 'REQUEST_DENIED'.

**Comment by tanis2000** [comment]
@TetrixGauss did you ever manage to solve this issue?

**Comment by fernandobracaroto** [comment]
For me, I had the enable Directions API.

**Comment by cantsaywisp1308** [comment]
I have the same issue too, REQUEST_DENIED
