### ISSUE TITLE
How can add lat long in waypoint.

### ISSUE THREAD

**Issue by alpitilanam** [Dammyololade/flutter_polyline_points#69]
I want add the lat long in way point, So I have implement like below:
wayPoints: [PolylineWayPoint(location: "23.3822748%2C74.0206771,23.2537885%2C74.1480252")],
but its' not working.
So please help me for this.
Thank you in Advance.

**Comment by rijazrasheed** [comment]
You need to add waypoints like this
wayPoints: [PolylineWayPoint(location: "via:23.3822748%2C74.0206771,23.2537885%2C74.1480252")],

Also if the travel mode is set to transit, you have to set atleast two waypoints.
