### ISSUE TITLE
Given polylines for route is not "snapped" to roads

### ISSUE THREAD

**Issue by Yahllil** [Dammyololade/flutter_polyline_points#70]
I am using the `flutter_polyline_points` package to draw a route between multiple points on my `GoogleMap` widget (providing start point, end point, and multiple points in between).

The polylines are being drawn perfectly fine, and everything seems to work, except for the fact that the polylines are not "snapped" to the roads, and seem like just a line between each point. Please see this example:

[![Exmaple image][1]][1]

I am getting the points for the polyline like this:

    PolylineResult result = await polylinePoints.getRouteBetweenCoordinates(
          kGooglePlacesAPIKey,
          PointLatLng(
            startPoint.latitude,
            startPoint.longitude,
          ),
          PointLatLng(
            endPoint.latitude,
            endPoint.longitude,
          ),
          wayPoints: myAddresses.map((currAddress) {
            return PolylineWayPoint(
              location: '${currAddress.latitude},${currAddress.longitude}',
            );
          }).toList(),
        );

Does anyone know why it is occurring? Is there a way to solve it using this package?

Thank you

  [1]: https://i.stack.imgur.com/DefbW.png

**Comment by Hectorc70** [comment]
Igual me sucede,al parecer solo sucede con distancias muy grandes

**Comment by guiiamorim** [comment]
@Yahllil did you find any solution for this? Can't seem to find any solution out there. I'm building my route the same way as you.

**Comment by rodrigo-badaro** [comment]
@guiiamorim I switched DIRECTIONS API for the ROUTES API.

the polylines provided by ROUTES API is more detailed and the lines follow the roads perfectly

**Comment by rodrigo-badaro** [comment]
![image](https://user-images.githubusercontent.com/116225043/208550972-2eaacd5a-960d-4136-89f2-b9c5d7799110.png)

**Comment by guiiamorim** [comment]
I see, will try this to see if it works, thanks!

**Comment by Dammyololade** [comment]
This has now been optimised with the new release [version 2.0.0](https://pub.dev/packages/flutter_polyline_points)
