### ISSUE TITLE
Received error code [OVER_QUERY_LIMIT] when using function getRouteBetweenCoordinates()

### ISSUE THREAD

**Issue by anhTuan0712** [Dammyololade/flutter_polyline_points#73]
Yesterday I was able to use it, but today when I called for the 2nd time it returned the error [OVER_QUERY_LIMIT].
I make sure I only call getRouteBetweenCoferences() 1 time at a time.
Statistics from my google API.
![image](https://user-images.githubusercontent.com/75367671/168565907-8016748e-3d4b-4e26-9245-78b9630e084a.png)
what should I do to solve this problem?

**Comment by Dammyololade** [comment]
Kindly check your google cloud configuration
