### ISSUE TITLE
How to get the travel duration in the result?

### ISSUE THREAD

**Issue by topex-psy** [Dammyololade/flutter_polyline_points#74]
It should be available in Google Directions API. We enable enable billing in google console not to just draw the lines.
Please add the duration based on `travelMode` in the `PolylineResult`.
Thank you in advance.

**Comment by BinniZenobioCordovaLeandro** [comment]
Related to PR Closed
https://github.com/Dammyololade/flutter_polyline_points/pull/13#issuecomment-1251797106

**Comment by BinniZenobioCordovaLeandro** [comment]
Related to PR #65 Opened
https://github.com/Dammyololade/flutter_polyline_points/pull/65#issuecomment-1251806811
