### ISSUE TITLE
XMLHttpRequest Error

### ISSUE THREAD

**Issue by sureshvickey** [Dammyololade/flutter_polyline_points#78]
getroutebetweencoordinates from flutter web creates XMLHttpRequest Error.

**Comment by vasuravada** [comment]
Me also getting the same error, any work around for this?

**Comment by Dammyololade** [comment]
Now available on [version 2.0.0](https://pub.dev/packages/flutter_polyline_points)

**Comment by wendellavila** [comment]
I'm still experiencing this on 2.0.0.
It only works when running with --web-browser-flag "--disable-web-security".

**Comment by wendellavila** [comment]
I found the cause for the error. To make a request to Google Maps from a browser you [must use the Javascript API](https://github.com/googlemaps/google-maps-services-js/issues/59#issuecomment-399626833). The Directions API doesn't support CORS and will return an XMLHttpRequest error when called from the client-side.

For now I wrote my own [solution](https://github.com/wendellavila/flutter_polyline_noXMLHttpRequestError) that uses the [google_maps](https://pub.dev/packages/google_maps) package to get the points and then uses your decoder to generate LatLng coordinates.
