### ISSUE TITLE
travelMode options

### ISSUE THREAD

**Issue by devzom** [Dammyololade/flutter_polyline_points#8]
I see in Your ex. a :   _travelMode: TravelMode.driving_ but don't get this implementations in this plugin? Is it deleted?

**Comment by whitecloud-sas** [comment]
same thing, and the polyline is returning to the Origin

**Comment by devzom** [comment]
Could You add polyline_mode parameter to method? 
There are 4 available option: 

- driving (default)
- walking
- bicycling
- transit

**Comment by Dammyololade** [comment]
Good day guys, this update will soon be made available on pub.dev sorry for late deployement

**Comment by Dammyololade** [comment]
The travel mode has been added and the package has been updated, thanks for the feedback

**Comment by emnfelix** [comment]
Travel mode does not work. I line 30 of network_util.dart you should change the parameter from "travelMode" to "mode" per https://developers.google.com/maps/documentation/directions/intro
