### ISSUE TITLE
Update the http version to latest in your pubspec.yaml

### ISSUE THREAD

**Issue by prenCodePad** [Dammyololade/flutter_polyline_points#83]
As you are using old http package version in your package, it is giving compatibility issues with other packages, please update the the http package with the latest version.

**Comment by anorld-droid** [comment]
I have also run into this issue,is this package still supported?

**Comment by dsgriffin** [comment]
Ran into this issue also when trying to upgrade to `http` version `1.0.0` @Dammyololade

**Comment by Dammyololade** [comment]
The fix will land shortly, so sorry for the delay @dsgriffin

**Comment by Dammyololade** [comment]
The [PR](https://github.com/Dammyololade/flutter_polyline_points/pull/85) has been merged to master. I'm planning a 2.0 version of this plugin to address major issues raised in here, until then you can make use of the master branch
