### ISSUE TITLE
Update the http version to latest in your pubspec.yaml

### ISSUE THREAD

**Issue by fadimanakilci** [Dammyololade/flutter_polyline_points#98]
Using old http package software in your package causes compatibility problems with other packages, please update the latest version of the http package.

**Comment by TetrixGauss** [comment]
Can you close that PR??? there are a lot packages depending on that package! and that is not the only problem! There are security issues.

https://github.com/advisories/GHSA-4rgh-jx4f-qfcq



@Dammyololade

**Comment by TetrixGauss** [comment]
@Dammyololade  great thank you!! are you going to upload a new version to get it to the other packages.

**Comment by TetrixGauss** [comment]
@Dammyololade  cool! if you need any help, dont hesitate!

**Comment by Dammyololade** [comment]
Published v2.0.1 🚀 thanks @fadimanakilci for the PR and @TetrixGauss for following up

**Comment by TetrixGauss** [comment]
@Dammyololade thank you so much!!!

**Comment by fadimanakilci** [comment]
You're welcome @Dammyololade. If there's anything I can help with please don't hesitate.
